/**
 * adyd spring data rest
 *
 * Contact: gilmith@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Fuerza { 
    id: number;
    probimpacto: number;
    ajusteDano: number;
    pesoTranspor: number;
    pesoMaximo?: number;
    abrirPuertas: string;
    doblarBarras: number;
}

