/**
 * adyd spring data rest
 *
 * Contact: gilmith@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Category } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CategoriaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * get de categoria por id
     * 
     * @param id 
     */
    findById(id: number, extraHttpRequestParams?: any): Observable<Category>;

    /**
     * get all categories
     * obtiene categorias por minino de.
     * @param fuerza valor de la habilidad de fuerza
     * @param inteligencia valor de la habilidad inteligencia
     * @param destreza valor de la habilidad destreza
     * @param constitucion 
     * @param sabiduria 
     * @param carisma 
     */
    findMinimo(fuerza: number, inteligencia: number, destreza: number, constitucion: number, sabiduria: number, carisma: number, extraHttpRequestParams?: any): Observable<Array<Category>>;

}
