/**
 * adyd spring data rest
 *
 * Contact: gilmith@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Sabiduria } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HabilidadesSabiduriaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param puntuacionBase tirada
     */
    habilidadesSabiduriaPuntuacionBaseGet(puntuacionBase: number, extraHttpRequestParams?: any): Observable<Sabiduria>;

}
