/**
 * adyd spring data rest
 *
 * Contact: gilmith@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Carisma } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HabilidadesCarismaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param puntuacionBase tirada
     */
    habilidadesCarismaPuntuacionBaseGet(puntuacionBase: number, extraHttpRequestParams?: any): Observable<Carisma>;

}
