/**
 * adyd spring data rest
 *
 * Contact: gilmith@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { Raza } from '../model/raza';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    RazaServiceInterface
} from './raza.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class RazaService extends BaseService implements RazaServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * get razas por puntuacion.
     * find razas disponbles por tirada de datos.
     * @param fuerza tirada de fuerza
     * @param destreza tirada de destreza
     * @param constitucion 
     * @param inteligencia 
     * @param sabiduria 
     * @param carisma 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public findRazaMinimo(fuerza: number, destreza: number, constitucion: number, inteligencia: number, sabiduria: number, carisma: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<Raza>>;
    public findRazaMinimo(fuerza: number, destreza: number, constitucion: number, inteligencia: number, sabiduria: number, carisma: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<Raza>>>;
    public findRazaMinimo(fuerza: number, destreza: number, constitucion: number, inteligencia: number, sabiduria: number, carisma: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<Raza>>>;
    public findRazaMinimo(fuerza: number, destreza: number, constitucion: number, inteligencia: number, sabiduria: number, carisma: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (fuerza === null || fuerza === undefined) {
            throw new Error('Required parameter fuerza was null or undefined when calling findRazaMinimo.');
        }
        if (destreza === null || destreza === undefined) {
            throw new Error('Required parameter destreza was null or undefined when calling findRazaMinimo.');
        }
        if (constitucion === null || constitucion === undefined) {
            throw new Error('Required parameter constitucion was null or undefined when calling findRazaMinimo.');
        }
        if (inteligencia === null || inteligencia === undefined) {
            throw new Error('Required parameter inteligencia was null or undefined when calling findRazaMinimo.');
        }
        if (sabiduria === null || sabiduria === undefined) {
            throw new Error('Required parameter sabiduria was null or undefined when calling findRazaMinimo.');
        }
        if (carisma === null || carisma === undefined) {
            throw new Error('Required parameter carisma was null or undefined when calling findRazaMinimo.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>fuerza, 'fuerza');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>destreza, 'destreza');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>constitucion, 'constitucion');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>inteligencia, 'inteligencia');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>sabiduria, 'sabiduria');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>carisma, 'carisma');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/raza/search/findMinimo`;
        return this.httpClient.request<Array<Raza>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find raza by ID.
     * Returns a single raza.
     * @param id ID of pet to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getRazaById(id: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Raza>;
    public getRazaById(id: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Raza>>;
    public getRazaById(id: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Raza>>;
    public getRazaById(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getRazaById.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/raza/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: undefined})}`;
        return this.httpClient.request<Raza>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
