/**
 * adyd spring data rest
 *
 * Contact: gilmith@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Raza } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RazaServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * get razas por puntuacion.
     * find razas disponbles por tirada de datos.
     * @param fuerza tirada de fuerza
     * @param destreza tirada de destreza
     * @param constitucion 
     * @param inteligencia 
     * @param sabiduria 
     * @param carisma 
     */
    findRazaMinimo(fuerza: number, destreza: number, constitucion: number, inteligencia: number, sabiduria: number, carisma: number, extraHttpRequestParams?: any): Observable<Array<Raza>>;

    /**
     * Find raza by ID.
     * Returns a single raza.
     * @param id ID of pet to return
     */
    getRazaById(id: number, extraHttpRequestParams?: any): Observable<Raza>;

}
