/**
 * adyd spring data rest
 *
 * Contact: gilmith@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TiradaSalvacion } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TiradasDeSalvacionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param nivel nivel del jugador
     * @param idCategoria categoria del personaje
     */
    tiradassalvacionSearchFindByCategoriaNivelGet(nivel: number, idCategoria: number, extraHttpRequestParams?: any): Observable<TiradaSalvacion>;

}
